# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# All the default Omarchy zsh configuration
# (don't mess with these directly, just add your customizations below!)
source ~/.local/share/omarchy/default/zsh/rc

# Add your own customizations below
